#!/usr/bin/env python3
from pyvis.network import Network 
from IPython.core.display import display, HTML
import pandas as pd


#create library of word connections:
reeves_text = open("reeves_tale.txt")
<<<<<<< Updated upstream
cleanedReeve = ''
ignore_list = ['a', 'the', 'and', 'i', 'of', 'to', 'in', 'was', 'is', 'by', 'is', 'that', 
               'for', 'but', 'no', 'be', 'there', 'on', 'at', 'my', 'it', 'will', 'with',
               'or', 'also', 'thou', 'you', 'we', 'up', 'can', 'which', 'yet', 'do', 'this', 'as',
               'not', 'shall', 'had', 'so', 'now', 'when', 'if', 'am', 'thee']
cleanedReeve = ''
=======
cleaned_reeve = ''
#all the words in reeve_nouns, reeve_adj, and reeve_verbs:
important_list = ['he', 'she','his','her','folk', 'business', 'absolon', 'nicholas', 'opinions', 'part', 'tale', 'man', 'Osewold', 'reeve', 'carpenters', 'craft', 'anger', 'heart', 'grouch', 'little', 'may', 'prosper', 'fruit', 'medlar', 'same', 'rubbish', 'straw', 'men', 'fear', 'fare', 'dance', 'world', 'pipe', 'sticks', 'nail', 'leek', 'power', 'desires', 'folly', 'anything', 'ashes', 'fire', 'coals', 'boasting', 'lying', 'greed', 'sparks', 'age', 'limbs', 'truth', 'years', 'tongue', 'chime', 'wretchedness', 'dotage', 'host', 'sermon', 'king', 'wit', 'day', 'holy', 'writ', 'devil', 'cobbler', 'shipman', 'physician', 'time', 'deptford', 'sires', 'displeased', 'fool', 'permissable', 'force', 'miller', 'terms', 'god', 'neck', 'piece', 'timber', 'trumpington', 'Cambridge', 'brook', 'bridge', 'mill', 'dwelling', 'peacock', 'bagpipe', 'fish', 'nets', 'game', 'belt', 'cutlass', 'blade', 'sword', 'dagger', 'pouch', 'peril', 'Sheffield', 'hose', 'face', 'nose', 'ape', 'skull', 'bully', 'person', 'hand', 'thief', 'grain', 'meal', 'sly', 'haughty', 'symkyn', 'wife', 'kin', 'parson', 'town', 'father', 'pan', 'brass', 'nunnery', 'holidays', 'tip', 'hood', 'gown', 'lady', 'water', 'ditch', 'disdain', 'cradle', 'boy', 'wench', 'eyes', 'glass', 'buttocks', 'breasts', 'hair', 'property', 'household', 'ancestry', 'churchs', 'goods', 'monopoly', 'milling', 'land', 'college', 'people', 'soler', 'hall', 'manciple', 'malady', 'fuss', 'scholars', 'mirth', 'amusement', 'buckler', 'sides', 'gear', 'guide', 'sack', 'head', 'hopper', 'trough', 'flour', 'bran', 'clerks', 'wolf', 'mare', 'foolish', 'clever', 'different', 'aggrieved', 'little', 'angry', 'old', 'dry', 'white', 'ripe', 'green', 'gone', 'continually', 'feeble', 'young', 'lordly', 'holy', 'waste', 'drunk', 'perilous', 'sharp', 'elegant', 'pug', 'bald', 'quarrelsome', 'brave', 'good-looking', 'thick', 'high', 'fair', 'headstrong', 'poor', 'eager', 'bold', 'implore', 'fast', 'done', 'ingenious', 'greatest', 'wisestfolk', 'wisest', 'laughed', 'enjoyed', 'saw', 'criticized', 'prosper', 'repay', 'blearing', 'tricking', 'wanted', 'speak', 'play', 'done', 'reveals', 'fear', 'ripe', 'dance', 'pipe', 'sticks', 'have', 'gone', 'talk', 'making', 'began', 'amounts', 'made', 'preach', 'say', 'waste', 'deplored', 'begin', 'pray', 'answer', 'make', 'repel', 'force', 'told', 'tricked', 'scorn', 'leave', 'break', 'see', 'called', 'carried', 'played', 'mend', 'shoot', 'fostered', 'would', 'preserve', 'went', 'flirt', 'dared', 'cut', 'jealous', 'dangerous', 'think', 'besmirched', 'lie', 'determined', 'raised', 'ground', 'happened', 'lay', 'thought', 'die', 'stole', 'complained', 'fuss', 'blustered', 'swore', 'implore', 'give', 'pledge', 'steal', 'trickery', 'rob', 'needed', 'guide', 'lays', 'spoke', 'fares', 'welcome', 'knows', 'serve', 'expect', 'grind', 'carry', 'speed', 'stand', 'wags', 'falls', 'trick', 'take', 'wisest']
#complete lists of noun, adjectives and verbs (generated by chatGPT):
reeve_nouns = ['i', 'he', 'she','his','her', 'folk', 'business', 'absolon', 'nicholas', 'opinions', 'part', 'tale', 'man', 'Osewold', 'reeve', 'carpenters', 'craft', 'anger', 'heart', 'grouch', 'little', 'may', 'prosper', 'fruit', 'medlar', 'same', 'rubbish', 'straw', 'men', 'fear', 'fare', 'dance', 'world', 'pipe', 'sticks', 'nail', 'leek', 'power', 'desires', 'folly', 'anything', 'ashes', 'fire', 'coals', 'boasting', 'lying', 'greed', 'sparks', 'age', 'limbs', 'truth', 'years', 'tongue', 'chime', 'wretchedness', 'dotage', 'host', 'sermon', 'king', 'wit', 'day', 'holy', 'writ', 'devil', 'cobbler', 'shipman', 'physician', 'time', 'deptford', 'sires', 'displeased', 'fool', 'permissable', 'force', 'miller', 'terms', 'god', 'neck', 'piece', 'timber', 'trumpington', 'Cambridge', 'brook', 'bridge', 'mill', 'dwelling', 'peacock', 'bagpipe', 'fish', 'nets', 'game', 'belt', 'cutlass', 'blade', 'sword', 'dagger', 'pouch', 'peril', 'Sheffield', 'hose', 'face', 'nose', 'ape', 'skull', 'bully', 'person', 'hand', 'thief', 'grain', 'meal', 'sly', 'haughty', 'symkyn', 'wife', 'kin', 'parson', 'town', 'father', 'pan', 'brass', 'nunnery', 'holidays', 'tip', 'hood', 'gown', 'lady', 'water', 'ditch', 'disdain', 'cradle', 'boy', 'wench', 'eyes', 'glass', 'buttocks', 'breasts', 'hair', 'property', 'household', 'ancestry', 'churchs', 'goods', 'monopoly', 'milling', 'land', 'college', 'people', 'soler', 'hall', 'manciple', 'malady', 'fuss', 'scholars', 'mirth', 'amusement', 'buckler', 'sides', 'gear', 'guide', 'sack', 'head', 'hopper', 'trough', 'flour', 'bran', 'clerks', 'wolf', 'mare']
reeve_adj = ['foolish', 'clever', 'different', 'aggrieved', 'little', 'angry', 'old', 'dry', 'white', 'ripe', 'green', 'gone', 'continually', 'feeble', 'young', 'lordly', 'holy', 'waste', 'drunk', 'perilous', 'sharp', 'elegant', 'pug', 'bald', 'quarrelsome', 'brave', 'good-looking', 'thick', 'high', 'fair', 'headstrong', 'poor', 'eager', 'bold', 'implore', 'fast', 'done', 'ingenious', 'greatest', 'wisestfolk', 'wisest']
reeve_verbs = ['laughed', 'enjoyed', 'saw', 'criticized', 'prosper', 'repay', 'blearing', 'tricking', 'wanted', 'speak', 'play', 'done', 'reveals', 'fear', 'ripe', 'dance', 'pipe', 'sticks', 'have', 'gone', 'talk', 'making', 'began', 'amounts', 'made', 'preach', 'say', 'waste', 'deplored', 'begin', 'pray', 'answer', 'make', 'repel', 'force', 'told', 'tricked', 'scorn', 'leave', 'break', 'see', 'called', 'carried', 'played', 'mend', 'shoot', 'fostered', 'would', 'preserve', 'went', 'flirt', 'dared', 'cut', 'jealous', 'dangerous', 'think', 'besmirched', 'lie', 'determined', 'raised', 'ground', 'happened', 'lay', 'thought', 'die', 'stole', 'complained', 'fuss', 'blustered', 'swore', 'implore', 'give', 'pledge', 'steal', 'trickery', 'rob', 'needed', 'guide', 'lays', 'spoke', 'fares', 'welcome', 'knows', 'serve', 'expect', 'grind', 'carry', 'speed', 'stand', 'wags', 'falls', 'trick', 'take', 'wisest']
#remove all the extra words that are not important:
cleaned_reeve = []
>>>>>>> Stashed changes
for line in reeves_text:
    line = line.lower()
    if line != "\n":
        for word in line.split(' '):
<<<<<<< Updated upstream
            word = ''.join(x for x in word if x.isalpha())
            if word != '':
                if word not in ignore_list:
                    cleanedReeve = cleanedReeve + ' '+ word
print(cleanedReeve)
wordDict = {}
clean_r_list = cleanedReeve.split(' ')
for index, word in enumerate(clean_r_list):
    if index < len(clean_r_list)-1:
        if word in wordDict:
            wordDict[word].append(clean_r_list[index + 1])
        else:
            wordDict[word] = [clean_r_list[index + 1]]
print(wordDict)
for key in wordDict:
    count = len(wordDict[key])
    net.add_node(key, label = key)
for key in wordDict:
    for word in wordDict[key]:
        net.add_edge(key, word) 
net.show('network_visual.html')
display(HTML('network_visual.html'))
=======
            if word in important_list:
                cleaned_reeve.append(word)

reeve_list = cleaned_reeve
list_length = len(reeve_list)
#reeve dict will connect nouns with adjectives and verbs:
reeve_dict = {}
#noun dict will connect nouns with other nouns:
noun_dict = {}
#MAIN NETWORK FUNCTION
for index, word in enumerate(cleaned_reeve):

    nearest_noun = ''
    nearest_adj = ''
    nearest_verb = ''
    if word in reeve_nouns:       
        #find next noun
        noun_index = index+1
        for word in reeve_list[index + 1: list_length]:
            if word not in reeve_nouns:
                noun_index = noun_index + 1
            else:
                break
        if noun_index < list_length:
            nearest_noun = reeve_list[noun_index]
        if noun_index >= len(reeve_list):
                nearest_noun = ''
                noun_index = list_length
        #find either adjective is previous word or next closest adjective after but not exceeding a noun
        if index > 1:
            if reeve_list[index-1] in reeve_adj:
                nearest_adj = reeve_list[index-1]
                adj_index = index - 1
            else:
                for adj_index, word in enumerate(reeve_list[index + 1 : noun_index]):
                    if word in reeve_adj:
                        nearest_adj = word
                        break
        #find closest trailing verb not exceeding another noun
        verb_index = index + 1
        for verb_index, word in enumerate(reeve_list[index+1: noun_index]):
            if word in reeve_verbs:
                nearest_verb = word
                break
        main_noun = reeve_list[index]
        #Add main_noun as a key in reeve dict
        if reeve_list[index] not in reeve_dict:
            reeve_dict[main_noun] = {}
        #Add main_noun as a key in noun dict
        if reeve_list[index] not in noun_dict:
            noun_dict[main_noun] = {}
        '''
        #Add nearest_noun as a key in noun dict
        if nearest_noun not in noun_dict:
            noun_dict[nearest_noun] = {}
        '''
        #If there is a nearest noun, add it as a value in noun dict:
        if nearest_noun != '':
            #ADD NEAREST NOUN TO MAIN NOUN'S DICTIONARY
            if nearest_noun not in noun_dict[main_noun]:
                noun_dict[main_noun][nearest_noun] = 1
            else:
                noun_dict[main_noun][nearest_noun] = noun_dict[main_noun][nearest_noun] + 1
            '''
            #ADD MAIN NOUN TO NEAREST NOUN'S DICTIONARY
            if main_noun not in noun_dict[nearest_noun]:
                noun_dict[nearest_noun][main_noun] = 1
            else:
                noun_dict[nearest_noun][main_noun] = noun_dict[nearest_noun][main_noun] + 1
            '''
        #if there is a nearest adjective, add it as a value in reeve dict
        if nearest_adj != '':
            if nearest_adj not in reeve_dict[main_noun]:
                reeve_dict[main_noun][nearest_adj] = 1
            else:
                reeve_dict[main_noun][nearest_adj] = reeve_dict[main_noun][nearest_adj] + 1
        #if there is a nearest verb, add it as a value in reeve dict
        if nearest_verb != '':
            if nearest_verb not in reeve_dict[main_noun]:
                reeve_dict[main_noun][nearest_verb] = 1
            else:
                reeve_dict[main_noun][nearest_verb] = reeve_dict[main_noun][nearest_verb] + 1

sorted_reeve_dict = sorted(reeve_dict.items(), key=lambda x:len(x[1]))

#CREATE THE ACTUAL NETWORK TO BE VISUALIZED:
adj_verb_net = Network()
noun_net = Network()
#reeve_dict dictionary format:
#{noun: {noun: #, verb: #, adj: #...}
#Create the Nodes
for word in important_list:
    adj_verb_net.add_node(word, word, title=word)
for word in reeve_nouns:
    noun_net.add_node(word, word, title=word)
#ADD EDGES:
for key in reeve_dict:
    for connection in reeve_dict[key]:      
        adj_verb_net.add_edge(key, connection, value=reeve_dict[key][connection])
for key in noun_dict:
    for connection in noun_dict[key]:
        noun_net.add_edge(key, connection, value=noun_dict[key][connection])

adj_verb_neighbor_map = adj_verb_net.get_adj_list()
# add neighbor data to node hover data
for node in adj_verb_net.nodes:
                node["title"] += " Neighbors:\n" + "\n".join(adj_verb_neighbor_map[node["id"]])
                node["value"] = len(adj_verb_neighbor_map[node["id"]])

noun_neighbor_map = noun_net.get_adj_list()
# add neighbor data to node hover data
for node in noun_net.nodes:
                node["title"] += " Neighbors:\n" + "\n".join(noun_neighbor_map[node["id"]])
                node["value"] = len(noun_neighbor_map[node["id"]])

adj_verb_net.show('adj_verb_net.html')
#display(HTML('adj_verb_net.html'))
noun_net.show('noun_net.html')
#display(HTML('noun_net.html'))

#Make the txt file:
output_reeves = open('network_output.txt', 'w')
output_reeves.write("NOUN TO ADJECTIVE AND VERB CONNECTIONS\n")
for item in sorted_reeve_dict:
    if item[1] != {}:
        print(item[0])
        print(item[1])
        output_reeves.write(item[0] + '\n' + "\t")
        for i, key in enumerate(item[1]):
            output_reeves.write(key + ": " + str(item[1][key]))
            if i < len(item[1]) - 1:
                output_reeves.write(', ')
            if i%7 == 0 and i > 1:
                output_reeves.write('\n\t')
        output_reeves.write("\n")
sorted_noun_dict = sorted(noun_dict.items(), key=lambda x:len(x[1]))
print("NOUN CONNECTIONS")
output_reeves.write("NOUN CONNECTIONS\n")
for item in sorted_noun_dict:
    if item[1] != {}:
        print(item[0])
        print(item[1])
        output_reeves.write(item[0] + '\n' + '\t')
        for i, key in enumerate(item[1]):
            output_reeves.write(key + ": " + str(item[1][key]))
            if i < len(item[1]) - 1:
                output_reeves.write(', ')
            if i%7 == 0 and i > 1:
                output_reeves.write('\n\t')
        output_reeves.write("\n")
>>>>>>> Stashed changes
